- name: configure Docker on EC2 Instances
  hosts: all
  become: true
  tasks:
    - name: updating apt
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start Docker Service
      service:
        name: docker
        state: started

    - name: Pull Docker Image
      command: docker pull raviraja0568/finance:1

    - name: Deploy Docker Container
      command: docker run -itd -p 8888:8081 raviraja0568/finance:1
